### ISSUE TITLE
Update README with more samples

### ISSUE THREAD

**Issue by gpailler** [gpailler/MegaApiClient#67]
Update README

- [x] Sample with progression (Add link from https://github.com/gpailler/MegaApiClient/issues/34#issuecomment-324276208)
- [x] Sample with options customization (application key, buffer size...)
- [x] Sample with download from a link
- [x] Sample with download using a stream (https://github.com/gpailler/MegaApiClient/issues/61#issuecomment-330066587)
- [x] Comment about UWP app and Json serialization (#69)
- [x] Proxy with authentication (#78)
- [x] Download limit 5GB for free accounts (#73)

**Comment by andyfmking** [comment]
Very handy plugin. Been trying to make use of Mega for quite sometime without any success till today. But the documentation of the plugin still make it hard to do somethings.

**AIM**
I want to get the link to the just uploaded file and send it to a database.

**EXAMPLE** 
If I have a screen with a file picker (for images), and a button for uploading the file to Mega.
After choosing my file and uploading it with the button, I want the path to the file so that I can put it in the imagesource of an image viewer on the app to display the image straight from Mega.

I tried your 

`INode myFile = client.UploadFile("MyFile.ext", myFolder);

Uri downloadUrl = `client.GetDownloadLink(myFile);`

But with no luck. When viewing the downloadUrl , it only had the backslash symbol.

This plugin is very helpful. Keep up the good work, I see this going very far.

Cheers from Tanzania.

**Comment by gpailler** [comment]
Hello,
The behavior you're describing is unexpected. I have unit tests testing this exact behavior and it seems they are working
![image](https://user-images.githubusercontent.com/3621529/30678263-36ba9a40-9ebb-11e7-9447-f57d45c0e853.png)

Could you attach a simple code to reproduce?

**Comment by andyfmking** [comment]
I edited my commented and showed that it works and brings back that correct link, but I still haven't figured out how to use that link with the ImageSource property of the Xamarin imageViewer, when the link is used as the imageSource, nothing shows in the image.
(for the case that the uploaded file is an image with correct .jpg extension)

**Comment by gpailler** [comment]
You cannot use the Uri from GetDownloadLink directly as a source for ImageSource. If you open this Uri in your browser, you will see Mega website with a button to download the file.

To achieve what you want, you should use `Download(Uri uri)` or `Download(INode node)` methods to retrieve a stream then use this stream as a source for your Image (https://stackoverflow.com/a/12232228)

**Comment by gpailler** [comment]
On 1.6.2
